"""
Decision rationale generator.

Builds the human-readable explanation that accompanies every decision. This
is what gets shown on the SOC dashboard and written to the audit log, so
clarity matters more than brevity.

The rationale is template-formatted, not generated by an ML model. Every
sentence in the output is fully traceable to a piece of data in the alert
or a rule in the classifier.
"""

from typing import Optional
from ..models.alert import Alert
from ..models.decision import Tier, Action, CriticalityBand


# Threat categories that automatically qualify as "extreme" regardless of CVSS.
# Mirrors EXTREME_THREAT_CATEGORIES in classifier.py — kept in sync deliberately
# so the rationale text accurately reflects what the classifier checked.
_EXTREME_CATEGORIES = {"ransomware", "active_exploitation"}


def build_rationale(
    alert: Alert,
    effective_score: int,
    effective_band: CriticalityBand,
    extreme_threat: bool,
    tier: Tier,
    action: Action,
    fail_safe_applied: bool,
    proposed_action_if_approved: Optional[Action] = None,
) -> str:
    """Compose a human-readable explanation of the decision.

    Output structure:
      1. Tier statement — what tier was selected and what it means.
      2. Asset criticality — score, band, and what the band means.
      3. Threat severity — CVSS or categorical severity that drove the decision.
      4. Tier 3 specifics — the two-phase flow, if applicable.
      5. Fail-safe note — surfaced loudly if the engine had to default.
    """
    parts = []

    # 1. Tier statement
    if tier == Tier.TIER_1:
        parts.append(_tier1_statement(action))
    elif tier == Tier.TIER_2:
        parts.append(_tier2_statement(effective_band, action))
    elif tier == Tier.TIER_3:
        parts.append(_tier3_statement(effective_band))

    # 2. Asset criticality (score + band + meaning)
    parts.append(
        f"Asset criticality: cc_score {effective_score} "
        f"({effective_band} band)."
    )

    # 3. Threat severity signal that drove the decision
    parts.append(_threat_signal_statement(alert, extreme_threat))

    # 4. Tier 3 — describe the two-phase flow explicitly so auditors and
    #    SOC analysts know exactly what's happening with the asset right now.
    if tier == Tier.TIER_3:
        parts.append(_tier3_flow_statement(proposed_action_if_approved))

    # 5. Fail-safe note. Auditors need to see this clearly.
    if fail_safe_applied:
        parts.append(
            f"Fail-safe applied: criticality_score was missing or out of "
            f"range, so the engine substituted score={effective_score} "
            f"({effective_band} band) per the cautious default."
        )

    return " ".join(parts)


# ---------- Tier statement helpers ----------

def _tier1_statement(action: Action) -> str:
    """Tier 1 statement, varying by which graduated action was selected."""
    if action == "log_only":
        return (
            "Tier 1 (log_only) selected: asset is non-critical and threat "
            "severity is low; the engine recorded the event without applying "
            "any disruptive containment."
        )
    if action == "block_port":
        return (
            "Tier 1 (block_port) selected: asset is non-critical and threat "
            "severity is medium; the engine applied a narrow, port-targeted "
            "containment proportional to the threat."
        )
    if action == "isolate_host":
        return (
            "Tier 1 (isolate_host) selected: asset is non-critical and threat "
            "severity is high or extreme; full host isolation is safe because "
            "no clinical workflows depend on this asset."
        )
    # Defensive default — should never hit given the classifier's mapping.
    return f"Tier 1 ({action}) selected: asset is non-critical."


def _tier2_statement(band: CriticalityBand, action: Action = "monitored_mode") -> str:
    """Tier 2 statement — varies by whether a flagged flow triggered throttling."""
    if action == "throttle":
        return (
            f"Tier 2 (throttle + Monitored Mode) selected: asset is {band} and the "
            f"threat is below the extreme threshold, but the SIEM flagged a "
            f"suspicious destination. The engine rate-limits that one flow — a "
            f"graded, non-disruptive containment scoped to the flagged dest — while "
            f"running Monitored Mode (deep telemetry, shadow auditing, zero "
            f"interference). Clinical traffic is untouched; only the flagged flow is "
            f"strangled. Patient care is not disrupted."
        )
    return (
        f"Tier 2 (Monitored Mode) selected: asset is {band} and the threat is "
        f"below the extreme threshold. Monitored Mode runs three components "
        f"in parallel: deep telemetry collection (every packet and system "
        f"call captured), shadow auditing (real-time comparison against a "
        f"clinical baseline), and zero interference (the device operates at "
        f"100% native functionality). No traffic is blocked. Patient care is "
        f"not disrupted."
    )


def _tier3_statement(band: CriticalityBand) -> str:
    """Tier 3 statement — the engine's part of the two-phase flow."""
    return (
        f"Tier 3 (await_clinician_approval) selected: asset is {band} AND the "
        f"threat is extreme. Disruptive containment may be required but must "
        f"be authorised by clinical staff."
    )


# ---------- Threat-signal helper ----------

def _threat_signal_statement(alert: Alert, extreme_threat: bool) -> str:
    """Describe the threat severity signal used by the classifier."""
    threat = alert.threat
    bits = []

    # Mirrors the classifier's own preference order: cas_score first, then
    # cvss_score, then the categorical fallback.
    if threat.cas_score is not None:
        bits.append(f"Threat CAS score (MediSIEM CAAP): {threat.cas_score}.")
    elif threat.cvss_score is not None:
        bits.append(f"Threat CVSS score: {threat.cvss_score}.")
    elif threat.technical_severity is not None:
        bits.append(f"Threat severity: {threat.technical_severity}.")
    else:
        bits.append("Threat severity: unknown.")

    # If the threat qualified as extreme via category, name the category so
    # auditors can see which trigger fired.
    if extreme_threat and threat.category and threat.category.lower() in _EXTREME_CATEGORIES:
        bits.append(
            f"Threat category '{threat.category}' is on the extreme-threat list."
        )
    elif extreme_threat and threat.cas_score is not None and threat.cas_score >= 9.0:
        bits.append("CAS score is in the extreme band (>=9.0).")
    elif extreme_threat and threat.cas_score is None and threat.cvss_score is not None and threat.cvss_score >= 9.0:
        bits.append("CVSS score is in the extreme band (>=9.0).")

    return " ".join(bits)


# ---------- Tier 3 flow helper ----------

def _tier3_flow_statement(proposed_action_if_approved: Optional[Action]) -> str:
    """Describe the two-phase Tier 3 flow.

    The asset is in Monitored Mode throughout — applied immediately by the
    Shuffle playbook in parallel with dispatching the clinician approval
    request. There is no unprotected gap.
    """
    proposed = proposed_action_if_approved or "isolate_host"
    return (
        f"Tier 3 flow: the affected device is immediately quarantined onto a "
        f"clinical-only segment (only its essential clinical peers reachable) AND "
        f"placed in Monitored Mode (deep telemetry + shadow auditing + zero "
        f"interference), in parallel with dispatching the clinician approval "
        f"request. Lateral movement is contained from the first millisecond. If the "
        f"clinician approves, the affected device escalates to '{proposed}' (full "
        f"isolation of that one device). If denied, it remains quarantined — "
        f"contained, with clinical telemetry preserved. The device is "
        f"non-disruptively contained throughout the entire flow."
    )
